# change the followings to match your Github username and repo name
# the name of your github repo
baseurl: "/"
# baseurl: "/portfolio"  # USE THIS ONLY FOR LOCALHOST

# the url of your github pages
url: "https://fuxlab.com"
# url: "http://localhost:4000" # USE THIS ONLY FOR LOCALHOST

# site information used in page title, meta data etc.
title: "Fuxlab"
description: "Digital Product Development, Hamburg"

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Fuxlab
author-bio: develops and invests in environment friendly, intelligent digital products.  # change to false to hide
author-image: fuxlab_transparent_black.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Products
  permalink: products
- text: Partner
  permalink: partner
- text: Insights
  permalink: insights
- text: About
  permalink: about
- text: Contact
  permalink: contact

# use false to turn off any social media links
twitter: https://twitter.com/fuxlab
facebook: https://facebook.com/fuxlab
instagram: https://instagram.com/fuxlab
github: https://github.com/fuxlab
linkedin: https://linkedin.com/company/fuxlab
youtube: https://youtube.com/@fuxlab
medium: false
google-scholar: false
email: https://fuxlab.com/contact

# footer information
footer-msg: "by Fuxlab GmbH"
footer-msg-link: https://fuxlab.com/contact/

# google analytics
google-analytics: UA-131500555-1

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag

collections:
  partners:
    type: true
    output: true
  products:
    output: true
  tools:
    output: true
